# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: my@mail.com
author_name: John Doe
code_tours: true
contract_name: verus_defense
deployment_language: python
ide_jetbrains: true
ide_vscode: true
preset_name: custom
project_name: verus_defense
python_linter: none
use_dispenser: true
use_github_actions: true
use_pre_commit: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

